name: 🐛 Проблема
title: '[Проблема] Краткое описание'
description: Сообщить о проблеме с ботом Discord-Dota-News
labels: ['type: проблема', 'status: нуждается в сортировке']

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ⚠️ Чеклист перед созданием issue
      description: |
        Пожалуйста, выполните эти пункты перед отправкой issue.
        Это поможет нам быстрее решить вашу проблему.
      options:
        - label: Я прочитал [README](https://github.com/Kasatikk/Discord-Dota-News/blob/main/README.md)
        - label: Я проверил [существующие issues](https://github.com/Kasatikk/Discord-Dota-News/issues)
        - label: Я убедился, что проблема не связана с моей конфигурацией
        - label: Я проверил работу API источников новостей

  - type: textarea
    id: description
    attributes:
      label: 🚨 Описание проблемы
      description: |
        Чётко опишите:
        - Что происходит?
        - Когда это началось?
        - Как это влияет на работу бота?
      placeholder: |
        Пример:
        "Бот запускается, но не присылает новости в канал #dota-news,
        хотя в консоли нет ошибок. Проблема появилась после обновления
        до версии 1.2.0"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 🌍 Окружение
      description: Укажите детали вашего окружения
      placeholder: |
        - ОС: [например Windows 11/Ubuntu 22.04]
        - Версия Python: [python --version]
        - Версия бота: [укажите версию из config.ini или название релиза]
        - Используемые API источники: [dotabuff, liquipedia и т.д.]
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔍 Шаги воспроизведения
      description: |
        Пошаговое руководство как воспроизвести проблему.
        Будьте максимально подробны!
      placeholder: |
        1. Запустите бота командой 'python main.py'
        2. Подождите 30 минут (интервал обновления)
        3. Проверьте канал #dota-news
        4. Ошибка: новости не приходят
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Ожидаемое поведение
      description: Что должно происходить в нормальных условиях?
      placeholder: |
        "Бот должен каждые 30 минут проверять новости на dotabuff
        и отправлять их в канал #dota-news"

  - type: textarea
    id: actual
    attributes:
      label: ❌ Фактическое поведение
      description: Что происходит вместо ожидаемого?
      placeholder: |
        "После 30 минут ожидания в канал не приходит ничего,
        хотя в консоли бота нет сообщений об ошибках"

  - type: textarea
    id: logs
    attributes:
      label: 📜 Логи и ошибки
      description: |
        Приложите соответствующие логи и сообщения об ошибках.
        Убедитесь, что удалили чувствительные данные (токены и т.д.)!
      placeholder: |
        ```
        2023-11-20 12:00: INFO: Бот запущен
        2023-11-20 12:30: ERROR: Ошибка подключения к dotabuff.com
        ```

  - type: textarea
    id: config
    attributes:
      label: ⚙️ Конфигурация
      description: |
        Приложите соответствующие части вашего config.ini
        (обязательно удалите токены и другую敏感 информацию!)
      placeholder: |
        ```ini
        [Dota]
        UpdateInterval = 30
        Sources = dotabuff, liquipedia
        ```

  - type: textarea
    id: additional
    attributes:
      label: 💡 Дополнительная информация
      description: |
        Любая другая информация, которая может помочь
        в решении проблемы
      placeholder: |
        - Пробовал менять интервал обновления - не помогло
        - На другом сервере бот работает нормально
        - Проблема появилась после обновления API dotabuff