name: Auto comment on new issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Прежде чем создавать issue, пожалуйста, ознакомьтесь с [README.md](https://github.com/Kasatikk/Discord-Dota-News/blob/main/README.md) - там есть ответы на частые вопросы.

            ### Основные шаги для диагностики:
            1. **Проверьте логи бота** - если есть ошибки, приложите их к issue
            2. **Убедитесь в корректности config.ini**:
               - Проверьте токен бота
               - Проверьте настройки каналов и ролей
               - Убедитесь в правильности интервала обновлений
            3. **Проверьте зависимости**:
               ```bash
               pip install -r requirements.txt
               ```

            ### Частые проблемы и решения:
            - **Бот не запускается**:
              - Убедитесь, что Python 3.8+ установлен
              - Проверьте права на файлы (особенно на Linux)
              - Попробуйте запустить с ключом `--debug`

            - **Новости не приходят**:
              - Проверьте настройки источников в config.ini
              - Убедитесь, что API источников доступно
              - Увеличьте интервал проверки (UpdateInterval)

            - **Бот не реагирует на команды**:
              - Проверьте префикс команд
              - Убедитесь, что бот имеет нужные права
              - Проверьте ID каналов/ролей в конфиге

            ### Прежде чем отправить issue:
            1. Приложите:
               - Соответствующие фрагменты конфига (без токена!)
               - Логи ошибок
               - Скриншоты проблемы (если применимо)
            2. Опишите:
               - Что вы ожидали получить
               - Что происходит вместо этого
               - Какие шаги по устранению уже пробовали

            Пример правильного issue:
            ```markdown
            **Проблема:** Бот запускается, но не присылает новости
            
            **Ожидаемое поведение:** Новости должны приходить каждые 30 минут
            
            **Конфиг:**
            ```ini
            [Dota]
            UpdateInterval = 30
            Sources = dotabuff
            ```
            
            **Логи:**
            ```
            2023-11-20 12:00: ERROR: Failed to fetch from dotabuff (403)
            ```
            ```