name: Issue Response Bot

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Welcome and Guide User
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🎉 Добро пожаловать! Спасибо за ваше обращение!

Пожалуйста, помогите нам лучше понять вашу задачу:

<details>
<summary><b>🐞 Для сообщения об ошибке</b></summary>

\`\`\`markdown
**Описание проблемы:**
[Четко опишите проблему]

**Шаги для воспроизведения:**
1. ...
2. ...
3. ...

**Ожидаемое поведение:**
[Что должно происходить]

**Фактическое поведение:**
[Что происходит на самом деле]

**Дополнительная информация:**
- Версия ПО: [например, 1.2.3]
- Скриншоты: [при необходимости]
- Логи: [если есть]
\`\`\`
</details>

<details>
<summary><b>✨ Для предложения улучшения</b></summary>

\`\`\`markdown
**Описание улучшения:**
[Что вы хотите предложить?]

**Почему это важно:**
[Объясните пользу для проекта]

**Пример использования:**
[Как это будет работать на практике?]

**Альтернативы:**
[Рассматривали ли вы другие варианты?]
\`\`\`
</details>

### 📌 Рекомендации:
1. Используйте шаблоны выше для структурирования информации
2. Прикрепляйте скриншоты/логи (перетащите файлы в окно комментария)
3. Один issue = одна проблема/предложение

Мы рассмотрим ваш запрос в ближайшее время! 💛
`
            })
