name: "Автоответы-2"

on:
  issues:
    types: [opened]
  workflow_dispatch:  # тестик

permissions:
  issues: write
  pull-requests: read

jobs:
  respond-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Process new issue
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Обработка
              if (!context.payload.issue) {
                core.warning('No issue found in payload');
                return;
              }

              // Изучение контекста отправка АПи
              const { issue } = context.payload;
              const { body, user, number, title } = issue;
              const { owner, repo } = context.repo;

              // туда-сюда
              if (user.login.includes('[bot]')) {
                console.log('Skipping bot message');
                return;
              }

              if (!body?.trim()) {
                await github.rest.issues.createComment({
                  issue_number: number,
                  owner,
                  repo,
                  body: "👋 Пожалуйста, добавьте описание к вашему issue!"
                });
                return;
              }

              // 4. Определяем тип issue
              const isBug = /error|bug|ошибка|проблема/i.test(body + title);
              const isFeature = /feature|enhancement|улучшение/i.test(body + title);

              // 5. Формируем персонализированный ответ
              let response = `## 👋 Привет, @${user.login}!\n\n`;
              
              if (isBug) {
                response += `### 🐞 Мы получили ваш отчет об ошибке\n`;
                response += `Пожалуйста, уточните:\n\n`;
                response += "- Точные шаги воспроизведения\n";
                response += "- Ожидаемое и фактическое поведение\n";
                response += "- Версии используемых компонентов\n";
                response += "- Логи/скриншоты (используйте \\\`код\\\` для форматирования)\n\n";
                response += "**Метка:** Добавлена `bug`\n";
              } else if (isFeature) {
                response += `### 💡 Спасибо за ваше предложение!\n`;
                response += `Помогите нам лучше понять вашу идею:\n\n`;
                response += "- Какую проблему это решит?\n";
                response += "- Есть ли альтернативные решения?\n";
                response += "- Пример использования\n\n";
                response += "**Метка:** Добавлена `enhancement`\n";
              } else {
                response += `### ❓ Мы получили ваш вопрос\n`;
                response += `Для быстрого ответа уточните:\n\n`;
                response += "- Что вы уже пробовали?\n";
                response += "- Какие результаты ожидаете?\n";
                response += "- Релевантные фрагменты кода\n\n";
                response += "**Метка:** Добавлена `question`\n";
              }

              response += `\n> 🔔 Это автоматическое сообщение. Мы ответим в ближайшее время!`;

              // 6. Отправляем комментарий
              await github.rest.issues.createComment({
                issue_number: number,
                owner,
                repo,
                body: response
              });

              // 7. Добавляем соответствующую метку
              const labels = isBug ? ['bug'] : isFeature ? ['enhancement'] : ['question'];
              
              await github.rest.issues.addLabels({
                issue_number: number,
                owner,
                repo,
                labels: [...labels, 'triage']  // Всегда добавляем метку triage
              });

              console.log(`Successfully processed issue #${number}`);

            } catch (error) {
              // 8. Обработка ошибок
              core.error(`Failed to process issue: ${error}`);
              core.setFailed(error.message);
            }
