name: Автоответ на issue

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:  # туда-сюда

env:
  BOT_NAME: "--"
  DOCS_URL: "${{ github.server_url }}/${{ github.repository }}/wiki"
  CODE_FORMAT: "```\n$CODE\n```"  # заворачивание ответа
jobs:
  process-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
    steps:
      - name: Analyze and respond
        uses: actions/github-script@v7
        id: respond
        with:
          script: |
            const { issue, repository } = context.payload;
            const { body, user, number } = issue;
            
            // Пропускаем свои же сообщения и пустые issues
            if (user.login.includes('[bot]') || !body?.trim()) {
              console.log('Skipping bot or empty issue');
              return;
            }

            // Анализ содержания issue
            const isBugReport = body.toLowerCase().includes('bug') || 
                              /error|issue|problem|ошибка|проблема/i.test(body);
            const isFeatureRequest = body.toLowerCase().includes('feature') || 
                                    /enhancement|improvement|улучшение/i.test(body);

            // AI -анализ и авто ответ АПИ
            let response = `## 👋 Привет, @${user.login}!\n\n`;
            
            if (isBugReport) {
              response += `### 🐞 Мы получили ваш баг-репорт\n`;
              response += `Для быстрого решения проблемы, пожалуйста, уточните:\n\n`;
              response += `1. **Точные шаги воспроизведения**\n`;
              response += `2. **Ожидаемое vs фактическое поведение**\n`;
              response += `3. **Версии используемых компонентов**\n`;
              response += `4. **Логи/скриншоты** (используйте ${env.CODE_FORMAT.replace('$CODE', 'код')} для логов)\n\n`;
              response += `🔍 *Мы уже начали анализ вашего отчета!*\n`;
            } else if (isFeatureRequest) {
              response += `### 💡 Спасибо за ваше предложение!\n`;
              response += `Помогите нам лучше понять вашу идею:\n\n`;
              response += `1. **Какую проблему это решит?**\n`;
              response += `2. **Есть ли альтернативные решения?**\n`;
              response += `3. **Пример использования**\n\n`;
              response += `📊 *Мы оценим ваше предложение в течение 48 часов*\n`;
            } else {
              response += `### ❓ Мы получили ваш вопрос\n`;
              response += `Для быстрого ответа уточните:\n\n`;
              response += `1. **Что вы уже пробовали?**\n`;
              response += `2. **Какие результаты ожидаете?**\n`;
              response += `3. **Релевантные фрагменты кода/конфигов**\n\n`;
              response += `📚 Возможно, ответ уже есть в [документации](${env.DOCS_URL})\n`;
            }

            // Добавляем стандартные блоки
            response += `\n<details>
            <summary><b>📝 Шаблон для ответа</b></summary>
            
            ${env.CODE_FORMAT.replace('$CODE', 
              isBugReport ? 
              '**Шаги воспроизведения:**\n1. ...\n\n**Ожидаемый результат:**\n...\n\n**Фактический результат:**\n...' : 
              '**Описание:**\n...\n\n**Обоснование:**\n...\n\n**Пример использования:**\n...'
            )}
            </details>`;

            response += `\n\n🔔 *Это автоматическое сообщение. Мы ответим в ближайшее время!*`;

            // Создаем комментарий
            await github.rest.issues.createComment({
              issue_number: number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });

            // Добавляем соответствующие метки
            const labels = [];
            if (isBugReport) labels.push('bug', 'needs-triage');
            else if (isFeatureRequest) labels.push('enhancement', 'under-review');
            else labels.push('question', 'needs-info');

            await github.rest.issues.addLabels({
              issue_number: number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labels
            });

            // Для feature requests создаем связанную дискуссию
            if (isFeatureRequest) {
              await github.rest.repos.createDiscussion({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Обсуждение FR: ${issue.title}`,
                body: `Связано с #${number}\n\n${issue.body}`,
                category: 'Ideas'
              });
            }

      - name: Log processing result
        if: always()
        run: echo "Issue #${{ github.event.issue.number }} processed by ${{ env.BOT_NAME }}"
